#!/bin/bash
# conf2bak.sh
# config saving algorithm
echo ''

# Set
DAT=$(date +"%y%m%d")
NAM=$(uname -n)

# check 3 arguments are given #
case $# in
    0) echo "usage: conf2bak [-h|-z|-e|-c location]"
	echo "try: -h for help"
	exit 0
	;;
    1) case "$1" in
        # display help message
	-h) echo "config backup editor @M"
	    echo "usage: conf2bak [--help|-z|-e|-c location]"
	    echo "       --help   displays this text"
	    echo "       -z       copies configs to zero (int hdd)"
	    echo "       -e       copies configs to exil (ext hdd)"
	    echo "       -c location     copies configs to specified location (see mount/blkid)"  
	    exit 0
	    ;;
        # loc = zero
	-z) LOC="/media/zero/projects/computer/linux/configs/"$USER"_"$NAM"_$DAT" #$USER gets evaluated via shell later on...
	    echo "copy configs > zero..."
	    ;;
        # loc = exil
	-e) LOC="/media/exil/projects/computer/linux/configs/"$USER"_"$NAM"_$DAT"
	    echo "copy configs > exil..."
	    ;;
        # error message
	*) echo "invalid option"
	   echo "usage: conf2bak [-h|-z|-e|-c location]"
	   echo "try: -h for help"
	   exit 0
	   ;;
       esac
       ;;
    2) #  loc = custom
       if [ $1 == "-c" ]; then
	   LOC="$2/configs_"$USER"_"$NAM"_$DAT"
	   echo "copy configs > wherever..."
       fi
       ;;
    *) # error message
       echo "invalid option"
       echo "usage: conf2bak [-h|-z|-e|-c location]"
       echo "try: -h for help"
       exit 0
       ;;
esac
echo ''


# init location
echo "setting up location..."
mkdir $LOC
echo "...done"; echo ''
echo "backup location: $LOC"
echo "...done"; echo ''

# copy scripts
echo "copy scripts..."
cp -R $HOME/scripts $LOC; echo "scripts/ >"
echo "{"; echo "$(ls $HOME/scripts)"; echo "}"
echo "...done"; echo ''

# copy xmonad
echo "copy xmonad..."
mkdir $LOC/.xmonad
cp -R $HOME/.xmonad/xmonad.hs* $LOC/.xmonad; echo ".xmonad/ >"
echo "{"; echo "$(ls $HOME/.xmonad | grep xmonad.hs*)"; echo "}"; echo ''

# copy rcs
echo "copy rcs..."
cp $/etc/fstab $LOC; echo "   fstab >"
echo "...done"; echo ''

# copy rcs
echo "copy rcs..."
cp $HOME/.bashrc $LOC; echo "   .bashrc >"
cp $HOME/.background.* $LOC; echo "   .background.* >"
cp $HOME/.conkyrc $LOC; echo "   .conkyrc >"
cp $HOME/.dircolors $LOC; echo "   .dircolors >"
cp $HOME/.emacs $LOC; echo "   .emacs >"
cp $HOME/.xinitrc $LOC; echo "   .xinitrc >"
cp $HOME/.xresources $LOC; echo "   .xresources >"
cp $HOME/.zshrc $LOC; echo "   .zshrc >"
cp $HOME/.moc/config $LOC/.moc_config; echo "   .moc/* >"
echo "...done"; echo ''

# copy notes
echo "copy notes..."
cp -R $HOME/notes $LOC; echo "notes >"
echo "{"; echo "$(ls $HOME/notes)"; echo "}"
echo "...done"; echo ''

# reminder
echo "keep in mind, this are rcs,they are invisible!"
touch '$LOC/here_are_invisible_files_cant_you_see?!' # strong votes cause of '?!'
echo "added reminder..."; echo ''

# end
echo "nothin else to do ... so doin nothin..."
echo "...done :)"; echo ''
