#!/bin/bash
# conky > dzen2 > statusbar 
# ~/scripts/conkyzen

#layout
wl=1420 #widh left
wr=500 #wl + wr = 1920
hu=16 #height up
hd=20
xl=0 #x pos left
xr=$wl
yd=1060 #y pos down
yu=0

#CONKYFILE="${HOME}/.conkyrc"
bar_tr="${HOME}/.conky/conkybartrrc"
bar_br="${HOME}/.conky/conkybarbrrc"
bar_bl="${HOME}/.conky/conkybarblrc"

#colors & style
fg="#9d9d9d"
bg="#000000"
style="-fg $fg -bg $bg -e ''"


#output
conky -c $bar_tr | dzen2 -x $xr -y $yu -h $hu -w $wr -ta 'r' $style & #top right bar
conky -c $bar_br | dzen2 -x $xr -y $yd -h $hd -w $wr -ta 'r' $style & #bottom right bar
conky -c $bar_bl | dzen2 -x $xl -y $yd -h $hd -w $wl -ta 'l' $style & #bottom left bar