#!/bin/bash

mute=`amixer get Master | grep "Mono:" | awk '{print $6}'`
if [ $mute == "[on]" ]
then
    vol=`amixer get Master | grep -oE "[[:digit:]]*%" | sed 's/%//'`
    if [ $vol == "0" ]
    then
        echo "Mute"
    else
        echo $vol
    fi
else
    echo "Mute"
fi
