#!/bin/bash
# fires up emacs server (if not running) & connects cia client!
# server stays alive as daemon!
# -c opens a new window instead of using the term.
# -a "" is a bit complicated, kinda bug use:D
# checkout emacsclient --help
#
# emacsclient -c -a ""